apiVersion: v1
kind: ReplicationController
metadata:
  name: dantest02
  namespace: com-att-ocnp-mgmt
spec:
  replicas: 1
  selector:
    app: dantest02
  template:
    metadata:
      labels:
        app: dantest02
    spec:
      serviceAccount: YOUR
      containers:
      - name: dantest02
        image: ${docker-registry}/${docker-namespace}/dantest02:latest
        imagePullPolicy: Always
        ports:
         - containerPort: 8080